source 'https://github.com/RedP4nda/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'RPRouter_Example' do
  pod 'RPRouter', :path => '../'

  target 'RPRouter_Tests' do
    inherit! :search_paths

    
  end
end
